### ISSUE TITLE
 ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by cesarvr** [feedhenry-raincatcher/raincatcher-demo-cloud#55]
Hi,
 
I have installed the three projects and npm install in each of them, so they just look fine, 
then I start the three projects using grunt and they look fine, then when I boot up the mobile app and after login in I get this error: 
 
`continuation-local-storage\node_modules\async-listener\glue.js:188:31
    Error creating event in the MBaaS: { Error: connect ECONNREFUSED 127.0.0.1:443
        at Object.exports._errnoException (util.js:1022:11)
        at exports._exceptionWithHostPort (util.js:1045:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 443 }`

node 7.4 
mongodb 2.4.9

any ideas ?
Thanks.

**Comment by Ki1L3r** [comment]
Cesar, I have just solved it. This appears when the node version is != 4.4.2, This was appearing running node v 4.7.3
